package com.example.presensor.data

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.presensor.data.entities.Course
import com.example.presensor.data.entities.Session
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

@RunWith(AndroidJUnit4::class)
class AppDatabaseTest {

    private lateinit var db: AppDatabase

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java).build()
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        db.close()
    }

    @Test
    fun insertSessionUpdatesCache() = runBlocking {
        val courseId = db.insertCourse(Course(name = "C1"))
        
        // Load course to initialize cache for it
        db.loadSessionsForCourse(Course(id = courseId, name = "C1"))
        
        db.insertSession(courseId, "New Session", 1000L)
        
        val cache = db.getCourseCache()
        assertEquals(courseId, cache.courseId)
        assertEquals(1, cache.allSessions.size)
        assertEquals("New Session", cache.allSessions[0].name)
        assertTrue(cache.sessionIds.contains(cache.allSessions[0].id))
    }

    @Test
    fun deleteSessionUpdatesCache() = runBlocking {
        val courseId = db.insertCourse(Course(name = "C1"))
        val session = Session(courseId = courseId, name = "S1", date = 1000L)
        db.insertSessions(listOf(session))
        
        // We need the ID generated by the DB
        val sessions = db.getSessionsByCourse(courseId)
        val sessionWithId = sessions[0]
        
        db.loadSessionsForCourse(Course(id = courseId, name = "C1"))
        
        db.deleteSession(sessionWithId)
        
        val cache = db.getCourseCache()
        assertTrue(cache.allSessions.isEmpty())
        assertTrue(cache.sessionIds.isEmpty())
    }
}
